# Generated by Medikit 0.8.0 on 2020-11-27.
# All changes will be overriden.
# Edit Projectfile and run “make update” (or “medikit update”) to regenerate.


PACKAGE ?= django_zero
PYTHON ?= $(shell which python || echo python)
PYTHON_BASENAME ?= $(shell basename $(PYTHON))
PYTHON_DIRNAME ?= $(shell dirname $(PYTHON))
PYTHON_REQUIREMENTS_FILE ?= requirements.txt
PYTHON_REQUIREMENTS_INLINE ?= 
PYTHON_REQUIREMENTS_CELERY_FILE ?= requirements-celery.txt
PYTHON_REQUIREMENTS_CELERY_INLINE ?= 
PYTHON_REQUIREMENTS_CHANNELS_FILE ?= requirements-channels.txt
PYTHON_REQUIREMENTS_CHANNELS_INLINE ?= 
PYTHON_REQUIREMENTS_DEV_FILE ?= requirements-dev.txt
PYTHON_REQUIREMENTS_DEV_INLINE ?= 
PYTHON_REQUIREMENTS_PROD_FILE ?= requirements-prod.txt
PYTHON_REQUIREMENTS_PROD_INLINE ?= 
QUICK ?= 
PIP ?= $(PYTHON) -m pip
PIP_INSTALL_OPTIONS ?= 
VERSION ?= $(shell git describe 2>/dev/null || git rev-parse --short HEAD)
BLACK ?= $(shell which black || echo black)
BLACK_OPTIONS ?= --line-length 120 --exclude '/(\.git|\.hg|\.mypy_cache|\.tox|\.venv|\.release|_build|buck-out|build|dist|node_modules|{{cookiecutter.name}})/'
ISORT ?= $(PYTHON) -m isort
ISORT_OPTIONS ?= --recursive --apply -s node_modules
PYTEST ?= $(PYTHON_DIRNAME)/pytest
PYTEST_OPTIONS ?= --capture=no --cov=$(PACKAGE) --cov-report html
VUEPRESS ?= $(shell which vuepress || echo vuepress)
VUEPRESS_SOURCEDIR ?= docs
YARN ?= $(shell which yarn || echo yarn)
NODE ?= $(shell which node || echo node)
MEDIKIT ?= $(PYTHON) -m medikit
MEDIKIT_UPDATE_OPTIONS ?= 
MEDIKIT_VERSION ?= 0.8.0

.PHONY: clean docs docs-deploy docs-dist format help install install-celery install-channels install-dev install-prod medikit quick release test testrun update update-requirements

install: .medikit/install   ## Installs the project.
.medikit/install: $(PYTHON_REQUIREMENTS_FILE) setup.py
	$(eval target := $(shell echo $@ | rev | cut -d/ -f1 | rev))
ifeq ($(filter quick,$(MAKECMDGOALS)),quick)
	@printf "Skipping \033[36m%s\033[0m because of \033[36mquick\033[0m target.\n" $(target)
else ifneq ($(QUICK),)
	@printf "Skipping \033[36m%s\033[0m because \033[36m$$QUICK\033[0m is not empty.\n" $(target)
else
	@printf "Applying \033[36m%s\033[0m target...\n" $(target)
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U "pip ~=19.0,<19.2" wheel
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U $(PYTHON_REQUIREMENTS_INLINE) -r $(PYTHON_REQUIREMENTS_FILE)
	$(YARN) install --production
	@mkdir -p .medikit; touch $@
endif

clean:   ## Cleans up the working copy.
	rm -rf build dist *.egg-info .medikit/install .medikit/install-dev .medikit/install-celery .medikit/install-channels .medikit/install-prod
	find . -name __pycache__ -type d | xargs rm -rf

install-dev: .medikit/install-dev   ## Installs the project (with dev dependencies).
.medikit/install-dev: $(PYTHON_REQUIREMENTS_DEV_FILE) setup.py
	$(eval target := $(shell echo $@ | rev | cut -d/ -f1 | rev))
ifeq ($(filter quick,$(MAKECMDGOALS)),quick)
	@printf "Skipping \033[36m%s\033[0m because of \033[36mquick\033[0m target.\n" $(target)
else ifneq ($(QUICK),)
	@printf "Skipping \033[36m%s\033[0m because \033[36m$$QUICK\033[0m is not empty.\n" $(target)
else
	@printf "Applying \033[36m%s\033[0m target...\n" $(target)
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U "pip ~=19.0,<19.2" wheel
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U $(PYTHON_REQUIREMENTS_DEV_INLINE) -r $(PYTHON_REQUIREMENTS_DEV_FILE)
	$(YARN) install
	@mkdir -p .medikit; touch $@
endif

quick:   #
	@printf ""

install-celery: .medikit/install-celery   ## Installs the project (with celery dependencies).
.medikit/install-celery: $(PYTHON_REQUIREMENTS_CELERY_FILE) setup.py
	$(eval target := $(shell echo $@ | rev | cut -d/ -f1 | rev))
ifeq ($(filter quick,$(MAKECMDGOALS)),quick)
	@printf "Skipping \033[36m%s\033[0m because of \033[36mquick\033[0m target.\n" $(target)
else ifneq ($(QUICK),)
	@printf "Skipping \033[36m%s\033[0m because \033[36m$$QUICK\033[0m is not empty.\n" $(target)
else
	@printf "Applying \033[36m%s\033[0m target...\n" $(target)
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U "pip ~=19.0,<19.2" wheel
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U $(PYTHON_REQUIREMENTS_CELERY_INLINE) -r $(PYTHON_REQUIREMENTS_CELERY_FILE)
	@mkdir -p .medikit; touch $@
endif

install-channels: .medikit/install-channels   ## Installs the project (with channels dependencies).
.medikit/install-channels: $(PYTHON_REQUIREMENTS_CHANNELS_FILE) setup.py
	$(eval target := $(shell echo $@ | rev | cut -d/ -f1 | rev))
ifeq ($(filter quick,$(MAKECMDGOALS)),quick)
	@printf "Skipping \033[36m%s\033[0m because of \033[36mquick\033[0m target.\n" $(target)
else ifneq ($(QUICK),)
	@printf "Skipping \033[36m%s\033[0m because \033[36m$$QUICK\033[0m is not empty.\n" $(target)
else
	@printf "Applying \033[36m%s\033[0m target...\n" $(target)
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U "pip ~=19.0,<19.2" wheel
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U $(PYTHON_REQUIREMENTS_CHANNELS_INLINE) -r $(PYTHON_REQUIREMENTS_CHANNELS_FILE)
	@mkdir -p .medikit; touch $@
endif

install-prod: .medikit/install-prod   ## Installs the project (with prod dependencies).
.medikit/install-prod: $(PYTHON_REQUIREMENTS_PROD_FILE) setup.py
	$(eval target := $(shell echo $@ | rev | cut -d/ -f1 | rev))
ifeq ($(filter quick,$(MAKECMDGOALS)),quick)
	@printf "Skipping \033[36m%s\033[0m because of \033[36mquick\033[0m target.\n" $(target)
else ifneq ($(QUICK),)
	@printf "Skipping \033[36m%s\033[0m because \033[36m$$QUICK\033[0m is not empty.\n" $(target)
else
	@printf "Applying \033[36m%s\033[0m target...\n" $(target)
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U "pip ~=19.0,<19.2" wheel
	$(PIP) install $(PIP_INSTALL_OPTIONS) -U $(PYTHON_REQUIREMENTS_PROD_INLINE) -r $(PYTHON_REQUIREMENTS_PROD_FILE)
	@mkdir -p .medikit; touch $@
endif

format: install-dev  ## Reformats the codebase (with black, isort).
	$(BLACK) $(BLACK_OPTIONS) . Projectfile
	$(ISORT) $(ISORT_OPTIONS) . Projectfile

test: install-dev  ## Runs the test suite.
	$(PYTEST) $(PYTEST_OPTIONS) tests

testrun:   ##
	$(eval TMPDIR := $(shell mktemp -d))
	(cd $(TMPDIR); $(PYTHON) -m virtualenv -p $(PYTHON) env)
	$(TMPDIR)/env/bin/pip install .[dev]
	$(eval ZERO := $(TMPDIR)/env/bin/django-zero)
	(cd $(TMPDIR); $(ZERO) create --no-input project acme)
	(cd $(TMPDIR)/acme; $(ZERO) install)
	(cd $(TMPDIR)/acme; $(ZERO) manage migrate)
	(cd $(TMPDIR)/acme; make start)
	trap 'rm -rf "$(TMPDIR)"' EXIT; (cd $(TMPDIR)/acme; $(ZERO) start)

release:   ## Releases django-zero.
	python -c 'import medikit; print(medikit.__version__)' || pip install medikit;
	$(PYTHON) -m medikit pipeline release start

docs:   ##
	$(VUEPRESS) dev docs

docs-dist:   ##
	$(VUEPRESS) build docs

docs-deploy: docs-dist  ##
	cd docs/.vuepress/dist && git init && git add -A && git commit -m "Build vuepress documentation." && git push -f git@github.com:django-zero/django-zero.github.io.git master

medikit:   # Checks installed medikit version and updates it if it is outdated.
	@$(PYTHON) -c 'import medikit, pip, sys; from packaging.version import Version; sys.exit(0 if (Version(medikit.__version__) >= Version("$(MEDIKIT_VERSION)")) and (Version(pip.__version__) < Version("10")) else 1)' || $(PYTHON) -m pip install -U "pip ~=19.0,<19.2" "medikit>=$(MEDIKIT_VERSION)"

update: medikit  ## Update project artifacts using medikit.
	$(MEDIKIT) update $(MEDIKIT_UPDATE_OPTIONS)

update-requirements:   ## Update project artifacts using medikit, including requirements files.
	MEDIKIT_UPDATE_OPTIONS="--override-requirements" $(MAKE) update

help:   ## Shows available commands.
	@echo "Available commands:"
	@echo
	@grep -E '^[a-zA-Z_-]+:.*?##[\s]?.*$$' --no-filename $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?##"}; {printf "    make \033[36m%-30s\033[0m %s\n", $$1, $$2}'
	@echo
